<!--  
Please note that I have added pyodide scripts (pyodide.js and webworker.js) inside the static/assets/js directory.
feel free to move them but you might run into issues that will require webpack loaders and a lot of debug time to get it running.
  
Finally, webworker.js file in public/pyodide/ have a link which fetches the python (pyodide) files from the internet. the pyodide files are pretty large and the cdn they offer isn't that fast but will do the job. we can host the pyodide files on our server/cdn/amazon storage. and replace the link in the webworker.js with our link which contains the pyodide files (this will improve the load speed of the interpreter). (Later) 
-->

<template>
  <div class="python-interpreter">
    <div class="python-interpreter__body">
      <!-- Problem Section -->
      <div class="python-interpreter__problem">
        <div class="container">
          <h2 class="problem-header">Problem 1: Fibonacci</h2>
          <div class="problem-body">
            <p>
              Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1
              and 2, the first 10 terms will be:
            </p>
            <p class="center code">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
            <p>
              By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the
              even-valued terms.
            </p>
          </div>
        </div>
      </div>
      <!-- Answer/Code section -->
      <div class="python-interpreter__editor">
        <div class="editor-area">
          <textarea id="code"></textarea>
        </div>
      </div>
      <!-- Output/Error section -->
      <div class="python-interpreter__output">
        <div class="output--toolbox">
          <h3 class="output--toolbox--header">Output</h3>
          <button @click="runCode" class="run-btn" :disabled="isRunButtonDisabled">Run</button>
        </div>
        <div class="output--info">
          <div class="output--header">
            Info: <small>{{ infoDisplay }}</small>
          </div>
        </div>
        <div class="output--code">
          <pre :class="{ 'run-error': isError }" class="output--code--result" v-html="resultDisplay"></pre>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import CodeMirror from "codemirror";
import "codemirror/mode/python/python.js";
export default {
  name: "PyInterpreter",
  data() {
    return {
      codeMirrorInstance: null,
      isRunButtonDisabled: true,
      pyodideWorker: null,
      resultDisplay: null,
      infoDisplay: null,
      isError: false
    };
  },
  methods: {
    initCodeMirror() {
      let codeMirrorInstance = CodeMirror.fromTextArea(document.getElementById("code"), {
        mode: "python",
        lineNumbers: true,
        gutter: true,
        lineWrapping: true
      });
      codeMirrorInstance.setSize("100%", "100%");
      codeMirrorInstance.setValue("\n".repeat(25));
      return codeMirrorInstance;
    },
    initPyodide() {
      let firstRun = true;
      this.infoDisplay = "Please wait, initializing...";
      //const pyodideWorker = new Worker("../assets/js/pyodide/web.worker.js");
      const pyodideWorker = new Worker("/static/assets/js/pyodide.worker.js");
      pyodideWorker.onerror = e => {
        this.resultDisplay = `error at ${e.filename}, Line: ${e.lineno}, ${e.message}`;
        this.isError = true;
      };
      pyodideWorker.addEventListener("message", e => {
        const { result, error } = e.data;
        this.isRunButtonDisabled = false;
        if (firstRun) {
          this.infoDisplay = "Initialized, you can run your code now";
          firstRun = false;
        } else {
          this.infoDisplay = "Run Complete";
        }
        if (result) {
          this.resultDisplay = JSON.parse(result).replace("\n", "<br>");
          this.isError = false;
        } else if (error) {
          this.resultDisplay = error.replace("\n", "<br>");
          this.isError = true;
        }
      });
      pyodideWorker.postMessage({
        python: "import sys; import io; sys.stdout = io.StringIO(); sys.stderr = io.StringIO();"
      });
      this.pyodideWorker = pyodideWorker;
    },
    async runCode() {
      this.resultDisplay = null;
      this.resultDisplay = null;
      this.isRunButtonDisabled = true;
      this.pyodideWorker.postMessage({ python: this.codeMirrorInstance.getValue() });
      this.infoDisplay = "Please wait, it may take quite a while if your code imports third party packages.";
    }
  },
  mounted() {
    this.codeMirrorInstance = this.initCodeMirror();
    this.initPyodide();
  }
};
</script>

<style scoped>
@import url("../../node_modules/codemirror/lib/codemirror.css");
.python-interpreter {
  height: 100%;
  max-width: 100%;
  overflow-x: hidden;
}
.python-interpreter__nav {
  width: 100%;
  padding: 10px;
  background-color: purple;
  color: white;
  display: flex;
  justify-content: space-around;
}

.python-interpreter__body {
  height: 100%;
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 2fr 1fr;
  color: grey;
}

.python-interpreter__problem {
  grid-row: 1/4;
}

.python-interpreter__problem,
.python-interpreter__editor,
.python-interpreter__output {
  max-height: 100%;
  overflow: auto;
}

/* The problem body */
.container {
  width: 95%;
  margin: auto;
}
.python-interpreter__problem {
  color: black;
  line-height: 1.8;
}
.problem-header {
  text-align: center;
}
.problem-body {
  text-align: justify;
  margin-top: 15px;
  font-size: 18px;
  font-weight: 100;
}
.center {
  text-align: center;
}
.code {
  opacity: 0.7;
}
/****************** */

.python-interpreter__editor {
  border-left: 2px solid black;
}
.python-interpreter__output {
  border-left: 2px solid black;
}
.output--toolbox {
  border-top: 2px solid black;
  border-right: 2px solid black;
  border-bottom: 2px solid black;
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.run-btn {
  color: white;
  background-color: navy;
  cursor: pointer;
  border: none;
  width: 50px;
  height: 35px;
}
.run-btn:hover {
  background-color: #4169e1;
}
.run-btn[disabled] {
  background-color: grey;
  color: black;
}

.output--header {
  font-size: 20px;
}
.output--toolbox--header {
  font-size: 24px;
}
.output--toolbox--header,
.output--info,
.output--code {
  margin-left: 15px;
}
.output--code {
  margin-top: 10px;
  color: black;
}
.run-error {
  color: red;
}

@media screen and (max-width: 720px) {
  .python-interpreter__body {
    grid-template-columns: 1fr;
    grid-template-rows: 1fr 2fr 1fr;
  }
  .python-interpreter__problem {
    grid-row: 1/2;
  }
  .python-interpreter__editor,
  .python-interpreter__output {
    border-left: none;
  }
}
</style>
